version: 2.1

# pipeline parameters
parameters:
  run-this-workflow:
    type: boolean
    default: false
  

jobs:
  foo:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run: echo FOO
  bar:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run: echo BAR

workflows:
  scheduled_pipeline:
    jobs:
      - foo
      - bar
    when:
      or:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - << pipeline.parameters.run-this-workflow >>
